Practice/Models/Guild.cs
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace Practice.Models
{
    public class Guild
    {
        [Key]
        public string Name { get; set; }
        public int MemberCount { get; set; }
        public string Team { get; set; }

    }

    public class GuildDBContext : DbContext
    {
        public DbSet<Guild> Guilds { get; set; }
    }
}

Practice/Models/Repository/GuildViewRepository.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace Practice.Models.Repository
{

    public interface IGuildViewer
    {
        SearchResult GetSqlResult(string sql);
    }

    public class GuildViewRepository : IGuildViewer
    {
        public SearchResult GetSqlResult(string sql)
        {
            using (var con = new GuildDBContext().Database.Connection)
            {
                var dbData = EachReader(con, sql);

                var result = new SearchResult { Result = new List<Tuple<string, List<object>>>(), SumDic = new Dictionary<int, decimal>() };

                var intCols = new List<int>();
                var decimalCols = new List<int>();

                foreach (var item in dbData)
                {
                    for (int i = 0; i < item.FieldCount; i++)
                    {
                        if (item.FieldCount > result.Result.Count)
                        {

                            if (item.GetFieldType(i) == typeof(int)) { intCols.Add(i); }
                            else if (item.GetFieldType(i) == typeof(decimal)) { decimalCols.Add(i); }

                            result.Result.Add(Tuple.Create(item.GetName(i), new List<object> { item[i] }));
                        }
                        else
                        {
                            result.Result[i].Item2.Add(item[i]);
                        }

                    }
                }

                foreach (var item in intCols)
                {
                    result.SumDic[item] = result.Result[item].Item2.OfType<int>().Sum();
                }
                foreach (var item in decimalCols)
                {
                    result.SumDic[item] = result.Result[item].Item2.OfType<decimal>().Sum();
                }

                return result;
            }
        }

        static IEnumerable<IDataRecord> EachReader(IDbConnection connection, string query)
        {
            using (var command = connection.CreateCommand())
            {
                command.CommandText = query;
                if (connection.State != ConnectionState.Open) connection.Open();

                using (var reader = command.ExecuteReader())
                {
                    while (!reader.IsClosed && reader.Read()) yield return reader;
                }
            }
        }
    }
}

Practice/Models/SearchResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Practice.Models
{
    public class SearchResult
    {
        public List<Tuple<string, List<object>>> Result { get; set; }
        public Dictionary<int, decimal> SumDic { get; set; }
    }
}

Practice/Controllers/GuildController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Practice.Models;

namespace Practice.Controllers
{
    public class GuildController : Controller
    {
        private GuildDBContext db = new GuildDBContext();

        //
        // GET: /Guild/

        public ActionResult Index()
        {
            return View(db.Guilds.ToList());
        }

        //
        // GET: /Guild/Details/5

        public ActionResult Details(string id = null)
        {
            Guild guild = db.Guilds.Find(id);
            if (guild == null)
            {
                return HttpNotFound();
            }
            return View(guild);
        }

        //
        // GET: /Guild/Create

        public ActionResult Create()
        {
            return View();
        }

        static string[] TEAM = { "Fox", "Penguin", "Bear" };
        //
        // POST: /Guild/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Guild guild)
        {
            if (ModelState.IsValid)
            {
                guild.Team = TEAM[new Random(Environment.TickCount).Next(3)];
                db.Guilds.Add(guild);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guild);
        }

        //
        // GET: /Guild/Edit/5
        public ActionResult Edit(string id = null)
        {
            Guild guild = db.Guilds.Find(id);
            if (guild == null)
            {
                return HttpNotFound();
            }
            return View(guild);
        }

        //
        // POST: /Guild/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Guild guild)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guild).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(guild);
        }

        //
        // GET: /Guild/Delete/5

        public ActionResult Delete(string id = null)
        {
            Guild guild = db.Guilds.Find(id);
            if (guild == null)
            {
                return HttpNotFound();
            }
            return View(guild);
        }

        //
        // POST: /Guild/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Guild guild = db.Guilds.Find(id);
            db.Guilds.Remove(guild);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Practice/Controllers/GuildViewController.cs
using Practice.Models;
using Practice.Models.Repository;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practice.Controllers
{
    public class GuildViewController : Controller
    {
        private IGuildViewer Repository { get; set; }

        public GuildViewController() : this(new GuildViewRepository()) { }
        public GuildViewController(IGuildViewer repo)
        {
            Repository = repo;
        }

        //
        // GET: /GuildView/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /GuildView/Result/[query]
        [HttpGet]
        public ActionResult Result(string query)
        {
            try
            {
                return View(Repository.GetSqlResult(query));
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

    }
}

Practice/Views/Guild/Create.cshtml
@model Practice.Models.Guild

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guild</legend>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MemberCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MemberCount)
            @Html.ValidationMessageFor(model => model.MemberCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Team) -> ?????
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practice/Views/Guild/Delete.cshtml
@model Practice.Models.Guild

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Guild</legend>
    
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MemberCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MemberCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Team)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Team)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Practice/Views/Guild/Details.cshtml
@model Practice.Models.Guild

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Guild</legend>
    
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MemberCount)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MemberCount)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Team)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Team)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Name }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Practice/Views/Guild/Edit.cshtml
@model Practice.Models.Guild

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guild</legend>
        @Model.Name

        @Html.HiddenFor(model => model.Name)

        <div class="editor-label">
            @Html.LabelFor(model => model.MemberCount)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MemberCount)
            @Html.ValidationMessageFor(model => model.MemberCount)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Team)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Team)
            @Html.ValidationMessageFor(model => model.Team)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Practice/Views/Guild/Index.cshtml
@model IEnumerable<Practice.Models.Guild>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>@Html.ActionLink("ViewData", "Index", "GuildView")</p>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MemberCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Team)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MemberCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Team)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Name }) |
            @Html.ActionLink("Details", "Details", new { id=item.Name }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Name })
        </td>
    </tr>
}

</table>

Practice/Views/GuildView/Index.cshtml
@{
    ViewBag.Title = "GuildView";
    const string TITLE = "queryTitle";
}

<h2>GuildViewer</h2>
<p>@Html.ActionLink("データ編集", "Index", "Guild")</p>
@using (Html.BeginForm("Result", "GuildView", FormMethod.Get))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>クエリ</legend>
        <div class="editor-label">
            タイトル(空の場合、履歴を残しません。)
        </div>
        <div class="editor-field">
            <input class="@TITLE text-box single-line" type="text" value="" />
        </div>

        <div class="editor-label">
            SQL
        </div>
        <div class="editor-field">
            <input id="query" class="text-box single-line" type="text" value="" name="query" style="width: 100%;" />
        </div>
        <p>
            <input type="submit" value="View" onclick="save()" />
        </p>
    </fieldset>
}
<p>
    your history
    <input type="button" onclick="clearHistory()" value="ClearHisory" />
</p>
<ul id="history" onload="refleshHisoty"></ul>


<h3>テーブル情報</h3>
<pre>   
テーブル名:Guilds
    [Name]        NVARCHAR
    [MemberCount] INT
    [Team]        NVARCHAR
</pre>
<h3>サンプル</h3>
<p>@Html.ActionLink("select * from Guilds", "result", new { query = "select * from Guilds" })</p>
<p>@Html.ActionLink("select Team,sum(MemberCount) as legion from Guilds group by Team", "result", new { query = "select Team,sum(MemberCount) as legion from Guilds group by Team" })</p>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function save() {
            var title = $(".@TITLE").val() == null ? "" : $(".@TITLE").val().trim();

            if (title.length <= 0) {
                return;
            }

            localStorage.setItem($(".@TITLE").val(), $("#query").val());
        }
        function clearHistory() {
            localStorage.clear();
            refleshHisoty();
        }
        function refleshHisoty() {
            $("#history").empty();
            for (var i in localStorage) {
                //もっと単純なエスケープがないだろうか
                $("#history").append("<li>" + "<a href=GuildView/Result/" + encodeURI(localStorage.getItem(i)) + ">" + $('<div/>').text(i).html() + "</li>");
            }
        }

        $("#history").ready(refleshHisoty);
    </script>
}

Practice/Views/GuildView/Result.cshtml
@model Practice.Models.SearchResult

@{
    ViewBag.Title = "Result";
    decimal num;
}
<style type="text/css">
    .Bar {
        background-color: #00ff21;
    }

    .BarContent {
        position: relative;
    }
</style>
<h2>Result</h2>
<table style="width: auto">
    <tr>
        @foreach (var item in Model.Result)
        {
            <th>
                @item.Item1
            </th>
        }
    </tr>
    @for (int i = 0; i < Model.Result.First().Item2.Count; i++)
    {
        <tr>
            @for (int j = 0; j < Model.Result.Count; j++)
            {
                <td>
                    @if (Model.SumDic.TryGetValue(j, out num))
                        
                    { <div class="Bar" style="width:@(((decimal.Parse(Model.Result[j].Item2[i].ToString()) / num) * 100).ToString("#0.##") )%;">
                        <div class="BarContent">@Model.Result[j].Item2[i]</div>
                    </div>
                    } else {
                        @Model.Result[j].Item2[i]
                    }
                </td>
            }
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Index", "Index")
</p>

Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>